// Binary STL generation, equivalent to dat2stl's stl_buffer + printf loop in
// bin/dat2stl, but binary format: 80-byte header, uint32 triangle count, then
// 50 bytes per facet (normal, 3 vertices as float32, uint16 attribute).
//
// Scaling matches _transvec in Parser.pm: value * mm_per_ldu (0.4) * scale.

import { MM_PER_LDU, calcSurfaceNormal } from './ldraw-parser.js';

// triangles: flat Float64Array/Array of 9 floats per triangle (LDU)
// Returns ArrayBuffer of the binary STL.
export function buildBinarySTL(triangles, scale = 1) {
    const numTriangles = triangles.length / 9;
    const buffer = new ArrayBuffer(84 + numTriangles * 50);
    const view = new DataView(buffer);
    const bytes = new Uint8Array(buffer);

    // 80-byte header. Note: many tools infer ASCII vs binary from the header
    // starting with "solid", so avoid that word.
    const header = 'binary STL generated by dat2stl web';
    for (let i = 0; i < header.length && i < 80; i++) {
        bytes[i] = header.charCodeAt(i);
    }
    view.setUint32(80, numTriangles, true);

    const m = MM_PER_LDU * scale;
    let offset = 84;
    const tri = [0, 0, 0, 0, 0, 0, 0, 0, 0];

    for (let t = 0; t < numTriangles; t++) {
        const base = t * 9;
        // Scale LDU -> mm and round to 4 decimals, like _transvec in Parser.pm,
        // then compute the normal from the rounded values (same as the Perl tool).
        for (let k = 0; k < 9; k++) {
            tri[k] = round4(triangles[base + k] * m);
        }
        const [nx, ny, nz] = calcSurfaceNormal(tri);

        view.setFloat32(offset, nx, true); offset += 4;
        view.setFloat32(offset, ny, true); offset += 4;
        view.setFloat32(offset, nz, true); offset += 4;
        for (let v = 0; v < 9; v++) {
            view.setFloat32(offset, tri[v], true);
            offset += 4;
        }
        view.setUint16(offset, 0, true);
        offset += 2;
    }

    return buffer;
}

function round4(v) {
    return parseFloat(v.toFixed(4));
}
